### ISSUE TITLE
Command format in NodeRed

### ISSUE THREAD

**Issue by LNS-MrGoodkat** [dionmes/node-red-contrib-philips-airjs#1]
Hi,
I try to send commands to my AC3033/10 observe and stop observing works, here is the JSON:

> [
>     {
>         "id": "378cf82f2fa4dcb6",
>         "type": "philips-airjs",
>         "z": "faae6f9a34c8716c",
>         "name": "philips-airjs",
>         "host": "xxx.xxx.xxx.xxx",
>         "x": 510,
>         "y": 800,
>         "wires": [
>             [
>                 "a3d98df264a9f266"
>             ]
>         ]
>     },
>     {
>         "id": "2f8b9f625040f02c",
>         "type": "inject",
>         "z": "faae6f9a34c8716c",
>         "name": "",
>         "props": [
>             {
>                 "p": "payload"
>             }
>         ],
>         "repeat": "",
>         "crontab": "",
>         "once": false,
>         "onceDelay": 0.1,
>         "topic": "",
>         "payload": "observe",
>         "payloadType": "str",
>         "x": 330,
>         "y": 800,
>         "wires": [
>             [
>                 "378cf82f2fa4dcb6"
>             ]
>         ]
>     },
>     {
>         "id": "a3d98df264a9f266",
>         "type": "debug",
>         "z": "faae6f9a34c8716c",
>         "name": "",
>         "active": true,
>         "tosidebar": true,
>         "console": false,
>         "tostatus": false,
>         "complete": "true",
>         "targetType": "full",
>         "statusVal": "",
>         "statusType": "auto",
>         "x": 670,
>         "y": 800,
>         "wires": []
>     },
>     {
>         "id": "8fea85325890424e",
>         "type": "inject",
>         "z": "faae6f9a34c8716c",
>         "name": "",
>         "props": [
>             {
>                 "p": "payload"
>             }
>         ],
>         "repeat": "",
>         "crontab": "",
>         "once": false,
>         "onceDelay": 0.1,
>         "topic": "",
>         "payload": "stop",
>         "payloadType": "str",
>         "x": 350,
>         "y": 760,
>         "wires": [
>             [
>                 "378cf82f2fa4dcb6"
>             ]
>         ]
>     },
>     {
>         "id": "ab54a4e07a6951ca",
>         "type": "inject",
>         "z": "faae6f9a34c8716c",
>         "name": "",
>         "props": [
>             {
>                 "p": "payload"
>             }
>         ],
>         "repeat": "",
>         "crontab": "",
>         "once": false,
>         "onceDelay": 0.1,
>         "topic": "",
>         "payload": "{\"mode\":\"S\"}",
>         "payloadType": "json",
>         "x": 330,
>         "y": 840,
>         "wires": [
>             [
>                 "378cf82f2fa4dcb6"
>             ]
>         ]
>     }
> ]

but I only get this message: 
`TypeError: msg.payload.toUpperCase is not a function`

is my command format wrong or how can I fix it?

**Comment by dionmes** [comment]
Ignore this. Found the issue, it was indeed in my code. Will update.

**Comment by LNS-MrGoodkat** [comment]
with the new update it is possible to set the mode 👍🏻.
is it possible to send 2 commands with one inject

e.g. sleep mode and turn off backlight?

**Comment by dionmes** [comment]
Yes, you can set the mode. But you can only send one command in a single payload. 0.2.3 is available and should fix it.
