### ISSUE TITLE
How to send payload that is not a string?

### ISSUE THREAD

**Issue by Chrischi-** [dionmes/node-red-contrib-philips-airjs#2]
Hey,

how do you send a payload that is not a string? (e.g.: aqil, cl)

`aqil 0` works (because zero = zero (hex, oct, etc.)) but `aqil 75`, `aqil 100` does not work.

Likewise, `cl true` does not work. Apparently, only commands that are _strings_ work.

Maybe someone can help or update the documentation with examples.

Many thanks in advance
:)

**Comment by dionmes** [comment]
Hi,
So around the aqil commando I am not sure. My device does not support different levels AFIK. The cl true should be converted to a boolean value. It works on my device.

**Comment by Chrischi-** [comment]
I use a 2889/10 and unfortunately `cl true` does not work here. But it could also 
be that the 2889 does not actually have a child lock. ;)

Only `aqil 0` works (so the command basically works already). I think the 2889 is expecting 
something other than a **string**.

by the way do you send all commands as a simple string or as a JSON object?

**Comment by dionmes** [comment]
It is a json object that gets stringified, encrypted and then send.

**Comment by Chrischi-** [comment]
i tried https://github.com/rgerganov/py-air-control and there the execution of `aqil` with the `coap` protocol works.

**Comment by Chrischi-** [comment]
I have fixed it by adding the following 
```
                        if (command == "aqil") {
                                commandValue = parseInt(commandValue, 10);
                        }
```
to `philips-airjs.js`

**Comment by dionmes** [comment]
Yes, I see it converts the value to int for some commands. Will also update.

**Comment by Chrischi-** [comment]
the following commands require customisation

`
rhset, aqil, dt
`
```

                        if ( command == "aqil" || command == "rhset" || command = "dt" ) {
                                commandValue = parseInt(commandValue, 10);
                        }

```

**Comment by Chrischi-** [comment]
with https://github.com/dionmes/node-red-contrib-philips-airjs/pull/5 this issue can be closed.
